title: "早安"
author: "陳映彤"
description: "WEB HOMEWORK"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html" ,title: "Home Change", icon: home}
  - {file: "README.md" ,title: "About me", icon: addres-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:410262236@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/marktuanbae"}
  - {title: Twitter, icon: twitter, url: "https://mobile.twitter.com/got77777_tuan"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
